config/routes.rb
Rails.application.routes.draw do
  # get 'teams/new', as: 'new_team'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "application#index"
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :teams, only: [:index, :new, :create, :show, :edit, :update] do 
    resources :lists, only: [:new, :create, :edit, :update]
    resources :tasks, only: [:new, :create, :edit, :update]
  end

  delete "/teams/:team_id/tasks/:id" => "tasks#destroy", as: :delete_task
  delete "/teams/:id" => "teams#destroy", as: :delete_team
  delete "/teams/:team_id/lists/:id" => "lists#destroy", as: :delete_list
end

app/models/User.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  def self.from_omniauth(auth) 
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name   
      user.last_name = auth.info.last_name
      user.user_name = auth.info.name
   end
  end

  has_many :tasks
  has_many :lists, through: :tasks
  belongs_to :team, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    validates :title, presence: true, uniqueness: true
    
    has_many :tasks, dependent: :destroy
    has_many :users, through: :tasks
    belongs_to :team
end

app/models/task.rb
class Task < ApplicationRecord
    validates :desc, presence: true
    
    belongs_to :user, optional: true 
    belongs_to :list
end

app/models/team.rb
class Team < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    validates :goal, presence: true

    has_many :users
    has_many :lists, dependent: :destroy
    has_many :tasks, through: :lists

    scope :team_members, -> { extract_associated(:users) }

    # unassociate team_members so user accounts don't have to be deleted
    def remove_team_members
        self.users.each do |user|
            user.team_id = nil 
            user.save
          end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index 
    end

    helpers do
        def resource_name
            :user
        end
        
        def resource_class 
            User 
        end
        
        def resource
            @resource ||= User.new
        end
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def new 
        @list = List.new
    end

    def create
        team = Team.find(params[:team_id])
        @list = team.lists.build(title: params[:list][:title])
        if @list.save 
            redirect_to team_path(team)
        else
            render :new
        end
    end

    def destroy 
        list = List.find(params[:id])
        @team = Team.find(params[:team_id])
        if list.destroy 
            redirect_to team_path(@team)
        else
            flash[:unsuccessful] = "Failed to delete list."
        end
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private 

    def sign_up_params
        # params.require(:user).permit(:user_name, :first_name, :last_name, :password, :password_confirmation)
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new 
    @team = Team.find(params[:team_id])
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    if task.save 
      redirect_to team_path(params[:team_id])
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
    @team_members = @task.list.team.users
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to team_path(@task.list.team)
    else
      render :edit
    end
  end

  def destroy
    task = Task.find(params[:id])
    list = List.find(task.list_id)
    if task.destroy 
      flash[:success] = "Successfully deleted task."
      redirect_to team_path(list.team_id)
    else
      flash[:unsuccessful] = "Failed to delete task."
    end
  end

  private 

  def task_params
    params.require(:task).permit(:desc, :user_id, :list_id)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def new
    @team = Team.new      
  end

  def create
    @team = Team.new(name: params[:team][:name], goal: params[:team][:goal])

    if @team.save
      @team.users << current_user
      redirect_to team_path(@team)
    else 
      render :new
    end
  end

  def show 
    @team = Team.find(params[:id])
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update 
    @team = Team.find(params[:id])
    if @team.update(new_team_params)
      flash[:success] = "Successfully updated team."
      redirect_to team_path(@team)
    else
      render :edit
    end
  end

  def destroy
    team = Team.find(params[:id])

    team.remove_team_members

    if team.destroy 
      flash[:success] = "Successfully deleted team."
      redirect_to root_path
    else
      flash[:unsuccessful] = "Failed to delete team."
    end
  end

  private 

  def new_team_params 
    params.require(:team).permit(:name, :goal)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    skip_before_action :verify_authenticity_token, only: :google_oauth2

    def google_oauth2
        @user = User.from_omniauth(request.env["omniauth.auth"])

        if @user.persisted? 
            sign_in_and_redirect @user, event: :authentication # will throw if user not activated
            set_flash_message(:notice, :success, kind: "Google") if is_navigational_format? 
        else
            session["devise.google_data"] = request.env["omniauth.auth"].except(:extra) # remove extra so session store doesn't overflow
            redirect_to new_user_registration_url
        end
    end

    def failure 
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/application/index.html.erb
<h1>Welcome to Task Team</h1>

<h2>What is Task Team?</h2>

<p>
Task Team is a group task-manager, designed to maximize collaboration and productivity.
To use Task Team, simply:
    <ul>
        <li>Create an account</li>
        <li>Create a team and add team members</li>
        <li>Add and assign tasks</li>
        <li>Collaborate!</li>
    </ul>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskTeam</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.6/build/pure-min.css" integrity="sha384-Uu6IeWbM+gzNVXJcM9XV3SohHtmWE+3VGi496jvgX1jyvDTXfdK+rfZc8C1Aehk5" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="pure-menu-horizontal">
    <ul class="pure-menu-list">
      <li class="pure-menu-item">
        <% if user_signed_in? && current_user.team %>
        <%= link_to "Your Team", team_path(current_user.team) %>
        <% elsif user_signed_in? && !current_user.team %>
        <%= link_to "Create Team", new_team_path %>
        <% end %>
      </li>
    </ul>
    </div>

    <%= yield %>

    <br /><br />
    <% if user_signed_in? %>
      <%= link_to "Log out", { controller: "devise/sessions", action: "destroy"}, method: :delete, class: "pure-button pure-button-primary" %>
    <% else %>
      <%= button_to "Sign in", user_session_path, class: "pure-button pure-button-primary" %><br />
      <%= button_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path, class: "pure-button pure-button-primary" %>
    <% end %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list, :url => url do |f| %>
   <%= f.text_field :title %>
   <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit List Title: </h1> 

<%= render partial: 'form', list: @list, locals: { :url => url_for(:controller => 'lists', :action => 'update') } %> 

app/views/lists/new.html.erb
<h1>List Title: </h1> 

<%= render partial: 'form', list: @list, locals: { :url => url_for(:controller => 'lists', :action => 'create') } %> 

app/views/tasks/_form.html.erb
<%= form_for @task, :url => url do |f| %>
    <h2>Description: </h2><%= f.text_field :desc %>

    <% if !@task.id %>
    <h3>Assign Task to List</h3>
    <%= f.collection_select(:list_id, @team.lists, :id, :title) %>

    <%= f.submit %>
    <% end %>

    <% if @task.id %>
    <h3>Assign Task to Team Member</h3>
    <%= f.collection_select(:user_id, @team_members, :id, :user_name) %>

    <%= f.submit %> or <%= link_to "Delete Task", delete_task_path(@task), :method => "delete" %>
    <% end %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render partial: 'form', locals: { task: @task, url: url_for(:controller => 'tasks', :action => 'update') } %>

app/views/tasks/new.html.erb
<h1>Create Task</h1>

<%= render partial: 'form', locals: { task: @task, url: { :controller => 'tasks', :action => 'create' } } %>